USE activity_service_dev; /*Change to your database name*/
GO

IF NOT EXISTS (
  SELECT *
    FROM sys.objects
   WHERE object_id = OBJECT_ID(N'[dbo].[ACTIVITY]')
     AND type = N'U'
)
BEGIN
  CREATE TABLE [dbo].[ACTIVITY] (
    [ID]              INT            IDENTITY(1,1) NOT NULL
       CONSTRAINT [PK_ACTIVITY] PRIMARY KEY,
    [ACTIVE]          BIT            NOT NULL CONSTRAINT [DF_ACTIVITY_ACTIVE] DEFAULT (1),
    [IS_DELETED]      BIT            NOT NULL CONSTRAINT [DF_ACTIVITY_IS_DELETED] DEFAULT (0),
    [TITLE]           NVARCHAR(200)  NOT NULL,
    [DESCRIPTION]     NVARCHAR(MAX)  NULL,
    [START_DATE]      DATETIME2(3)   NOT NULL,
    [END_DATE]        DATETIME2(3)   NULL,
    [CREATED_DATE]    DATETIME2(3)   NOT NULL CONSTRAINT [DF_ACTIVITY_CREATED_DATE] DEFAULT SYSUTCDATETIME(),
    [MODIFIED_DATE]   DATETIME2(3)   NOT NULL CONSTRAINT [DF_ACTIVITY_MODIFIED_DATE] DEFAULT SYSUTCDATETIME(),
    [CREATED_BY_ID]   NVARCHAR(50)   NULL,
    [MODIFIED_BY_ID]  NVARCHAR(50)   NULL
  );
END
GO