# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  pull_request:
    branches: ['**']

permissions:
  contents: read

jobs:
  build:
    # runs-on: ubuntu-24.04
    runs-on: [self-hosted, Linux, X64, activity]

    env:
      SERVICE_NAME: ${{ vars.SERVICE_NAME }}
      DB_SERVER_DEV: ${{ secrets.DB_SERVER_DEV }}
      DB_DATABASE_DEV: ${{ secrets.DB_DATABASE_DEV }}
      DB_DATABASE_PORT: ${{ secrets.DB_DATABASE_PORT }}
      DB_USERNAME_DEV: ${{ secrets.DB_USERNAME_DEV }}
      DB_PASSWORD_DEV: ${{ secrets.DB_PASSWORD_DEV }}
      DB_DRIVER_DEV: ${{ secrets.DB_DRIVER_DEV }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      WEB_FE_ORIGIN: ${{ secrets.WEB_FE_ORIGIN }}
      PATIENT_BE_ORIGIN: ${{ secrets.PATIENT_BE_ORIGIN }}
      RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST_STG }}
      RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
      RABBITMQ_USERNAME: ${{ secrets.RABBITMQ_USER }}
      RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASS }}
      RABBITMQ_VIRTUAL_HOST: ${{ secrets.RABBITMQ_VIRTUAL_HOST }}

    steps:
      - uses: actions/checkout@v4

      # Temporary step to debug ODBC installation issues
      - name: Check ODBC Installation
        run: |
          echo "=== Checking ODBC Installation ==="
          echo "1. Checking if odbcinst command exists:"
          which odbcinst || echo "odbcinst not found"
          
          echo -e "\n2. Checking ODBC configuration:"
          odbcinst -j || echo "unixODBC not installed"
          
          echo -e "\n3. Listing installed ODBC drivers:"
          odbcinst -q -d || echo "No drivers found or unixODBC not installed"
          
          echo -e "\n4. Checking for SQL Server ODBC driver files:"
          ls -la /opt/microsoft/msodbcsql*/lib64/ 2>/dev/null || echo "SQL Server ODBC drivers not found"
          
          echo -e "\n5. Checking odbcinst.ini file:"
          cat /etc/odbcinst.ini 2>/dev/null || echo "odbcinst.ini not found"




      - name: Set up Python 3.9.19
        uses: actions/setup-python@v3
        with:
          python-version: '3.9.19'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Check app imports
        run: |
          python -c "from app.main import app; print('All imports successful')"

      - name: Test unit tests with pytest
        run: |
          python -m pytest tests/unit

      - name: Test integration tests with pytest
        env:
          DB_SERVER_DEV: ${{ secrets.DB_SERVER_DEV }}
          DB_DATABASE_DEV: "fyp_dev_bryan_activity_test"
          # DB_USERNAME_DEV: ${{ secrets.DB_USERNAME_DEV }}
          # DB_PASSWORD_DEV: ${{ secrets.DB_PASSWORD_DEV }}
          DB_USERNAME_DEV: "sa"
          DB_PASSWORD_DEV: "Fyppear@3"
          DB_DRIVER_DEV: "ODBC Driver 18 for SQL Server"
        run: |
          python -m pytest tests/integration
